# File: templates/build_deploy_java_app.yml
parameters:
- name: ecosystemId
- name: app # name of the parameter; required
  type: object # data type of the parameter; required
- name: appGroup
  type: object

jobs:
- job: ${{ app.name }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: ${{ app.repo }}
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'package'
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)
  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'manifests'
      path: 'manifests'    