# pipeline for building ephemeral environment


trigger:
- master

parameters:
- name: ecosystemId
  type: string
  default: "01"
- name: ecosystemName
  type: string
  default: "staging"
- name: appGroups
  type: object
  default:
  - name: mb
    projectName: "mbApps"
    apps:
    - name: "mobileBanking"
      repo: 'git://mobile banking/retail'
      deployment_template: 'build_deploy_swift_app'
    - name: "mobileBanking"
      repo: 'git://mobile banking/bff/retail'
      deployment_template: 'build_deploy_java_app'
  - name: ib
    projectName: "ibApps"
    apps:
    - name: "internetBanking"
      repo: 'git://internet banking/retail'
      deployment_template: 'build_deploy_angular_app'
    - name: "mobileBanking"
      repo: 'git://internet banking/bff/retail'
      deployment_template: 'build_deploy_nodejs_app'   
  - name: accounts
    projectName: "ibApps"
    apps:
    - name: "accountsAPI"
      repo: 'git://accounts/api'
      deployment_template: 'build_deploy_angular_app'
    - name: "accounts"
      repo: 'git://internet banking/bff/retail'
      deployment_template: 'build_deploy_nodejs_app'        

pool:
  vmImage: ubuntu-latest

stages:
- stage: Initialize
  jobs:
  - job: Validate
    steps:
    - bash: echo "validate inputs"

- stage: Build_deploy
  jobs:
  - ${{ each appGroup in parameters.appGroups }}:
    - ${{ each app in parameters.appGroup.apps }}:
      - template: templates/${{app.deployment_template}}
        parameters:
          app: ${{ app }}

