Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: PV64
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
 
Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.micro
        SecurityGroups:
          - Ref: InstanceSecurityGroup
        KeyName: 
          Ref: KeyName
        ImageId: ami-0fc61db8544a617ed
      LaunchTemplateName: MyLaunchTemplate
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate: 
         LaunchTemplateName: MyLaunchTemplate
         Version: 1
      InstanceType: t2.micro
      KeyName:
        Ref: KeyName
    DependsOn: MyLaunchTemplate           
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable http access via port 8080 and ssh access on 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '8080'
        ToPort: '8080'
        CidrIp: 0.0.0.0/0            
